andikleen/pmu-tools

tl-serve.py
"tl-serve.py --gen" fails due to  missing argument when gencsv() is called
Also the generated files had   ":"  instead of "." in the name. 
C2:TopLevel.csv -> C2.TopLevel.csv
=> tl-serve: Fix generating HTML files

tl-serve.py
The regexp was not matching smt cores (e.g C0-T0).
=> tl-serve: Fix SMT support	

simple-pebs/simple-pebs.c
start_stop_cpu is called as
smp_call_function_single(cpu, start_stop_cpu,
(void *)(long)(cmd == SIMPLE_PEBS_START), 1);
so we need to enable the counters if arg is true.
=> simple-pebs: fix start_stop_cpu

jevents/README.md
This is a .py file.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
=> jevents: Fix typo in event_download.sh

toplev.py
Hey,
I've fixed the url for toplev-kernel-support wiki page that is shown on `toplev.py --help`.
=> Fix toplev-kernel-support url

jevents/cache.c
The event-rmap program wasn't working correctly.  It would return "br_misp_retired.all_branches" for all queries:
```
nate@skylake:~/git/pmu-tools-nkurz/jevents$ ./listevents | grep interrupt
hw_interrupts.received                   cpu/umask=0x01,period=100003,event=0xcb/
nate@skylake:~/git/pmu-tools-nkurz/jevents$ ./showevent hw_interrupts.received
cpu/config=0x1cb,name=hw_interrupts.received/
nate@skylake:~/git/pmu-tools-nkurz/jevents$ ./event-rmap 0x1cb
1cb: br_misp_retired.all_branches : All mispredicted macro branch instructions retired
nate@skylake:~/git/pmu-tools-nkurz/jevents$ ./event-rmap 0x1
1: br_misp_retired.all_branches : All mispredicted macro branch instructions retired
```
The problem was a reuse of the variable name "event" in the rmap_event() function in cache.c.  It …
=> Fix rmap_event() to match target event provided

jevents/Makefile, jevents/examples/Makefile, jevents/session.c
Quiet a couple warnings so that real issues are more apparent.  Clang still has some other noisy warnings, and ICC doesn't like '-Wno-unused-result, but both compile.
=> Quiet GCC 5.3 warnings for unused results and uninitialized variable

simple-pebs/simple-pebs.c
Haswell_EP and _EX (Xeon E5 v3 and Xeon E7 v3) have the 0x1c2 counter as well, so they must be supported. I guess almost all recent models support 0x1c2, but many of them are missing.
However I just added model number 63 (Haswell_EP and _EX) because at least for this model I can be sure by actually measuring it.
=> support haswell-ep and -ex

simple-pebs/simple-pebs.c
added Skylake support:
- new model number
- extended pebs_record format (IA32_PERF_CAPABILITIES[11:8] == 3)
=> simple-pebs: support Skylake

jevents/cache.c, jevents/jevents.h, jevents/resolve.c
Since the string is only read, change char * to const char * for
const-correctness.
=> const-correct event name in  resolve_event

jevents/perf-iter.c
The logic about whether part of event data is at the end of buffer is
reversed.
Signed-off-by: "Huang, Ying" <ying.huang@intel.com>
=> perf_buffer_read: Fix buffer wraps logic

jevents/Makefile, jevents/libjevents.spec
This commit provides two things. First, changes to the Makefile: adds
-fPIC to the CFLAGS so others can link to the library correctly, and
fixes the PREFIX to use DESTDIR so rpmbuild will work correctly.
Second, a minimum specfile necessary to build the RPM.
=> Provide necessary changes to build a libjevents RPM.

jevents/perf-iter.c
unistd.h is included twice. In case of alpine 3.7 with musl C, the unistd.h does not reside under <sys>
=> unistd.h location change

jevents/rdpmc.c
ICC does not have `__builtin_ia32_rdpmc`, instead one has to use intel-specific builtins.
=> Add support for ICC specific rdpmc

jevents/Makefile, jevents/cache.c, jevents/resolve.c
As discussed, remove the `pmu` parameter, add header.
=> remove pmu arg from callback in walk_perf_events, fixes #142

snb_client_ratios.py, tl_output.py, tl_stat.py, tl_uval.py, toplev.py
This PR consists of one upgrade for the statistics ~~and one new cmd line option~~.
For calculations that are being made, the standard deviation and mux are now [properly tracked](https://en.wikipedia.org/w/index.php?title=Propagation_of_uncertainty&oldid=858197377), so that the final result shows ratios +/- error margins, e.g.: 
```
FE             Frontend_Bound:                     14.35 +-     0.35 % Slots below           
BAD            Bad_Speculation:                     0.73 +-     0.45 % Slots below           
BE             Backend_Bound:                      49.01 +-     0.66 % Slots                 
RET            Retiring:                           35.94 +-     0.33 % Slots below
```
A simplistic version of this was already present before, but the errors were incorrectly …
=> Add proper error propagation and option for absolute values

jevents/resolve.c
=> allow name attribute in new-style raw event strings, fixes #162

COPYING
The old license had mostly a wrong street address.
By comparing old and new version, it turned out, some formatting
was changed.
This fixes https://github.com/andikleen/pmu-tools/issues/175
=> Update GPL 2 to updated GPL 2.

toplev.py
map(...) returns an iterable object that must be converted to a tuple when using python 3.
Tested on:
- Ubuntu 21.04
- Linux 5.11.0-31-generic
- Python 3.9.5
=> Fix not subscriptable map error

jevents/jevents.c, jevents/json.c, jevents/resolve.c
Fix double free in resolve.c:
There is possible double free when calling ``` jevent_free_extra ```.
The memory is allocated in ```jevent_copy_extra```. The ```gl_pathv``` in ```glob_t``` is an array of char pointers. The function copied the pointers, but not the strings they point to. Later when memory was freed with ```globfree``` in ```jevent_free_extra()``` it could cause double free and undefined behavior. Now the strings pointed in array are copied one by one.
Fix possible issue with providing null pointer to ```strdup``` in jevents.c.
If event description was missing in input JSON file, the ```desc``` variable was left as NULL in ```json_events()```. It was later provided to ```strdup``` in ```collect_events()```. Now the ```desc``` is initialized to default string if not found in …
=> jevents: fix some stability issues

jevents/resolve.c, jevents/session.c
This PR includes one bug fix and one major feature:
1. In `resolve.c`, we initialized `next_pmu` to `1`, which causes all but the first PMU to collect the event: I didn't notice this until I finished implementing this feature.
2. Added support for grouped multi-PMU events.
=> Grouped Multi-PMU Events

toplev.py
Currently invalid nodes are not caught, and before 1c232723 they were caught
but not printed because the map object was consumed by "all".
This uses map to compute "valid" again, as before 1c232723, but promotes the map
object to a list so that it can be evaluated more than once.
=> Fix "Unknown node(s)" diagnostic

README.md, event_download.py, jevents/cache.c
Hi Andi,
This pull request swaps the previous download.01.org URL with GitHub. We merged `readme.txt` into `README.md` and those file paths are updated here as well. Please review when you get a minute. Additional steps/details are also tracked in the parent issue at https://github.com/intel/perfmon/issues/17 . Sorry again about any extra work or interruption this causes.
```
ed@ebaker-MOBL3:~/pmu-tools$ rm -r ~/.cache/pmu-events/
ed@ebaker-MOBL3:~/pmu-tools$ ./event_download.py -a
Downloading https://raw.githubusercontent.com/intel/perfmon/main/mapfile.csv to mapfile.csv
Downloading https://raw.githubusercontent.com/intel/perfmon/main/NHM-EX/events/NehalemEX_core.json to GenuineIntel-6-2E-core.json
Downloading https://raw.githubusercontent.com/intel/perfmon/main/NHM-EP/events/NehalemEP_co …
```
=> event_download: Fetch events from GitHub

event_download.py
With the event defintions now hosted on Github it is now fairly simple
to download all CPU definitions in one go.
This patch allows overriding the download prefix url via an env var
allowing an easier offline workflow:
Some offline version of this, e.g.: download the zips from github
```
/tmp/offline$ git clone https://github.com/intel/perfmon
/tmp/offline$ git clone https://github.com/andikleen/pmu-tools
```
followed by
```
/tmp/offline$ PERFMONDIR=file:///tmp/offline/perfmon ./pmu-tools/event_download.py
Downloading file:///tmp/offline/perfmon/mapfile.csv to mapfile.csv
Downloading file:///tmp/offline/perfmon/ADL/events/alderlake_gracemont_core.json to GenuineIntel-6-97-hybridcore.json
Downloading file:///tmp/offline/perfmon/ADL/events/alderlake_goldencove_core.json to …
```
=> event_download: Allow specifying path to perfmon dir

ocperf.py
Recently a Header was introduced to Intel event files [1]. This commit checks for the presence of the new structure and pulls events from 'Events' accordingly.
[1] https://github.com/intel/perfmon/issues/22
=> ocperf: Retrieve events from updated JSON structure

pebs-grabber/pebs-grabber.c, pebs-grabber/pebs.h
1. support pebs v3
2. I don't have a CPU with pebs_v4, and I'm not quite sure how to present the pebs record for v4 in a better way. Therefore, I haven't submitted support for v4 related features.
=> pebs v3 support

.github/workflows/workflow.yml, pyproject.toml
I've enabled automated CalVersioning. The main benefit is that we don't have to store the previous version to generate the new version.
Con:
We don't know the current version from code.
One more request:
- Please remove the authorization for my repo from your pypi account. I pushed to master and then it updated to your pypi account's releases.
=> Enable automatic version bumping with bumpver

ocperf.py, pyproject.toml
This PR is a proof of concept that enables me to use ocperf for PGO while using pmu-tools as an installable artifact (https://gcc.gnu.org/wiki/AutoFDO/Tutorial). 
Test Plan:
Instead of adding pmu tools to my path:
1. I created a venv
2. pip install .
3. went to a directory not containing ocperf and then ran the following commands
```
which ocperf
/home/snihalani/pmu-tools/venv/bin/ocperf
cat /home/snihalani/pmu-tools/venv/bin/ocperf
import re
import sys
from ocperf import main
if __name__ == '__main__':
sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
sys.exit(main())
ocperf record ls
perf record ls
perf.data  test_file
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.015 MB perf.data (11 samples) ]
((venv) )
ocperf script
perf script …
```
=> Enable migration for ocperf into an installable script
